[project]
name = "practice"
version = "0.1.0"
description = "学习交付"
readme = "README.md"
authors = [
    { name = "kzymc", email = "jnvclsio@163.com" }
]
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "fastapi>=0.141.1",
    "jieba>=0.42.1",
    "openai>=3.26.0",
    "pypdf>=6.19.0",
    "tenacity>=9.1.4",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
practice = "practice:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
